-- 각 아이스크림의 성분 타입, 성분타입에 대한 총주문량
-- 정렬은 총주문량 ASC
SELECT * FROM (
    SELECT 
    INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM FIRST_HALF FH
    JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
    GROUP BY INGREDIENT_TYPE
) ORDER BY TOTAL_ORDER ASC