-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(PRICE * AMOUNT) as TOTAL_SALES
FROM FOOD_ORDER FO
JOIN FOOD_PRODUCT FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE TO_CHAR(FO.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY FO.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY SUM(PRICE * AMOUNT) DESC, PRODUCT_ID ASC